name: Docker Image Build and run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: stell0/financealerts:latest
    - name: Run the Docker container
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TICKER_LIST: ${{ vars.TICKER_LIST }}
        INDICATORS: ${{ vars.INDICATORS }}
      run: docker run -e TELEGRAM_CHAT_ID -e TELEGRAM_BOT_TOKEN -e TICKER_LIST -e INDICATORS stell0/financealerts:latest

