name: Docker Image Build and run

on:
  pull_request:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: stell0/financealerts:S(date +%s)
    - name: Run the Docker container
      env:
        TICKER_LIST: ${{ vars.TICKER_LIST }}
      run: docker run stell0/financealerts:latest
      
